// 由 scripts/gen-banner.mjs 產生，請勿手動修改。
// 每個字元是一個像素，對應 PALETTE 的 xterm 256 色；「.」為透明。
export const ART_WIDTH = 78;
export const PALETTE = {"o":52,"f":215,"s":166,"c":223,"w":231,"k":16,"n":211,"r":160,"R":124,"b":33,"B":25,"d":237,"t":238,"m":247,"p":251,"h":244,"y":179,"Y":94,"x":117,"l":229,"g":248,"v":252};
export const PIXELS = [
  ".......................................o............oo",
  "......................................ofo..........offo",
  "......................................offo........offfo",
  "......................................offfo......offffo",
  "......................................offnfo....offnffo",
  "...................ooo................offnnfooooffnnffo",
  ".................oofffo...............offnnffffffnnnffo",
  "................offffffo..............offnfssssssffnffo",
  "...............offfssffo..............offffssssssfffffo",
  "...............offfossffo.............offfffffffffffffo",
  "..............offfo.oofo...o..........offffffffffffffo..........xx",
  "..............offfo...o..ooroooo......offffffffffffffo....xxxxxxxx",
  "..............offfo.....orrrrrrroooooooffffwkfffwkfffo....xkxxx.xx",
  "..............ofsso......ooorrrrrrosfffffffkkffckkfffo..yooxxyyyy",
  "..............offsso........ooffrrrooffffffffcccccfffo.ooyyyYyYyy",
  "..............offfo........oofffssrrrrffffffccnncccffo..yyyyYyYyy",
  "..............osfffo.....oofRRRRRRRoorrrrffffcoocccfo..ooYyyYyYy",
  "..............ossssfo...offffsffRRoRRRRrrrrrrorrofffo..o.ooyYyYy",
  "...............ooffffoooofffffsfffffRRRcrrrrrrrrrffoooocoyyyyyYy",
  ".................offfffffffffffffffffffccccrrrffffffffccco",
  ".vvvvvv...........offffffffffffffffffffccccfffffffffffcccod",
  ".vvvvvv............offfffffffffffffffffffoooooooofffoooco",
  "....................ooofffffffffffffffffo........oood..o........vv",
  ".......................oooofffffffffffoo...........bb......ll.vv",
  "vvvvv.........tt...........ooffffffffobbbbbbbbbbbbbbbb.....ll.vvvv",
  "vvvvv......tttttttt.........offffffffobbbbbbbb......bb..tttttttvv",
  ".........tttttttttttt.....BBofffffffffo.............bbtttttttttttt",
  "........tttmmmmmmmmttt...BB..offoooffffo............bbttmmmmmmmmttt",
  "..vvvv.tttmm....p.mmtttBBB...offo..offffo.........bbbbbmm....p.mmttt",
  "..vvvvtttm.p....p...mtBB.....offfo..offfo.......bbbbttbbp....p...mttt",
  "......ttm..pp..p....BBBt......offoo.offffo....bbbb.ttm.bbp..p.....mtt",
  ".....ttmm...p..p...BBmmtt.....occcco.offfo..bbbb..ttmm..bb..p...ppmmtt",
  ".....ttm.....p.p..BB..mtt......oooo..osssobbbb....ttm....bb.p..pp..mtt",
  ".....ttmpp...pppBB....mtt.........hhhosffobb......ttmpp...bbppp....mtt",
  "....tttm..pppphBBBBB..mttt.......hhb.hoffo.......tttm..ppppbhp.....mttt",
  "....tttm.....phBBBBBBBBBBBBBBBBBBhBBbboffo.......tttm.....phhpppp..mttt",
  ".....ttm....ppppp...ppmtt......BBhBBd.offo........ttm....ppppp...ppmtt",
  ".....ttm..pp..p.p.....mtt........hh.ddoffo........ttm..pp..p.p.....mtt",
  ".....ttmmpp...p..p...mmtt.........hhhdoffo........ttmmpp...p..p...mmtt",
  "..g...ttm.....p..pp..mtt.............ofcco.........ttm.....p..pp..mtt",
  "......tgtm...p....p.mttt.............occcco........tttm...p....p.mttt",
  ".......tttmm.p....mmttt..............doooo..........tttmm.p....mmttt",
  "....g...tttmmmmmmmmttt...............................tttmmmmmmmmttt",
  ".........tttttttttttt.................................tttttttttttt",
  "...........tttttttt.....................................tttttttt",
  "ggg..ggg..ggg.tggg..ggg..ggg..ggg..ggg..ggg..ggg..ggg..ggg.tggg..ggg..ggg..ggg",
];
